python-django-celery-with-redis (3.0-1) unstable; urgency=low

  * Initial release (Closes: #nnnn)  <nnnn is the bug number of your ITP>

 -- Romain Acciari <romain.acciari@openio.io>  Wed, 14 Sep 2016 14:47:09 +0000
